-- ============================================================================
-- UROO.Admin — Supabase schema
-- Mirror of the Laravel (MySQL) tables used by the mobile app, using BIGINT
-- primary keys so IDs & FKs are identical on both sides for seamless 2-way
-- sync. RLS restricts rows by auth.uid() via users.supabase_uid.
--
-- Run this in the Supabase SQL editor. Then enable Realtime when desired.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. users (bigint PK, links to auth.users via supabase_uid uuid)
-- ----------------------------------------------------------------------------
create table if not exists public.users (
  id              bigint generated by default as identity primary key,
  name            text not null,
  email           text not null unique,
  email_verified_at timestamptz,
  password        text,                 -- nullable (mobile uses Supabase Auth)
  remember_token  text,
  supabase_uid    uuid unique,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- Keep updated_at fresh for sync watermarks
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- Create users row automatically when a Supabase Auth user signs up
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.users (name, email, supabase_uid)
  values (
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    new.email,
    new.id
  )
  on conflict (supabase_uid) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Security: allow the authenticated app to read its own row
create policy "users own row"
  on public.users for select
  using (supabase_uid = auth.uid());

-- ----------------------------------------------------------------------------
-- 2. Feature tables (all share the same shape & RLS pattern)
-- ----------------------------------------------------------------------------

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  company text,
  notes text,
  status text not null default 'active',
  deleted_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  name text not null,
  description text,
  category text,
  status text not null default 'development',
  progress integer not null default 0,
  platform text,
  tech_stack jsonb,
  storage_usage bigint not null default 0,
  start_date date,
  deadline date,
  completed_at date,
  deleted_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  invoice_number text not null unique,
  items jsonb not null default '[]',
  subtotal numeric(15,2) not null default 0,
  tax_percent numeric(5,2) not null default 0,
  tax_amount numeric(15,2) not null default 0,
  discount_percent numeric(5,2) not null default 0,
  discount_amount numeric(15,2) not null default 0,
  total numeric(15,2) not null default 0,
  paid_amount numeric(15,2) not null default 0,
  status text not null default 'hutang',
  due_date date,
  paid_at timestamptz,
  notes text,
  deleted_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.invoice_payments (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoices(id) on delete cascade,
  amount numeric(15,2) not null,
  remaining_after numeric(15,2) not null,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.app_ideas (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  tagline text,
  description text,
  features jsonb,
  tech_stack jsonb,
  platform text not null default 'web',
  status text not null default 'draft',
  priority text not null default 'medium',
  tags jsonb,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.brain_dumps (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  content text not null,
  is_pinned boolean not null default false,
  is_archived boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  content text not null default '',
  category text,
  tags jsonb,
  is_pinned boolean not null default false,
  is_favorite boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.savings_goals (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  target_amount numeric(15,2) not null,
  current_amount numeric(15,2) not null default 0,
  icon text,
  color text,
  deadline date,
  is_completed boolean not null default false,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.savings_transactions (
  id bigint generated by default as identity primary key,
  goal_id bigint not null references public.savings_goals(id) on delete cascade,
  type text not null,
  amount numeric(15,2) not null,
  description text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Add extra web tables (mirrored; used when syncing more modules later)
create table if not exists public.repositories (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  full_name text not null unique,
  description text,
  url text,
  language text,
  stars integer not null default 0,
  forks integer not null default 0,
  open_issues integer not null default 0,
  default_branch text not null default 'main',
  is_private boolean not null default false,
  is_archived boolean not null default false,
  last_pushed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.commits (
  id bigint generated by default as identity primary key,
  repository_id bigint not null references public.repositories(id) on delete cascade,
  sha text not null unique,
  message text not null,
  author_name text,
  author_email text,
  branch text not null default 'main',
  modifications jsonb,
  additions integer not null default 0,
  deletions integer not null default 0,
  committed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  provider text,
  category text,
  monthly_cost numeric(10,2),
  annual_cost numeric(10,2),
  currency text not null default 'IDR',
  billing_cycle text not null default 'monthly',
  due_date date not null,
  payment_status text not null default 'unpaid',
  reminder_days integer not null default 3,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ----------------------------------------------------------------------------
-- 3. updated_at triggers
-- ----------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'public.users','public.clients','public.projects','public.invoices',
    'public.invoice_payments','public.app_ideas','public.brain_dumps',
    'public.notes','public.savings_goals','public.savings_transactions',
    'public.repositories','public.commits','public.subscriptions'
  ] loop
    execute format(
      'drop trigger if exists trg_set_updated_at on %I.%I',
      split_part(t, '.', 1), split_part(t, '.', 2));
    execute format(
      'create trigger trg_set_updated_at before update on %I.%I
       for each row execute function public.set_updated_at()',
      split_part(t, '.', 1), split_part(t, '.', 2));
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- 4. Row Level Security
-- ----------------------------------------------------------------------------

-- Helper: return the user's integer id for the current auth.uid()
create or replace function public.current_user_id()
returns bigint language sql stable security definer set search_path = public as $$
  select id from public.users where supabase_uid = auth.uid();
$$;

do $$
declare tables text[] := array[
  'clients','projects','invoices','app_ideas',
  'brain_dumps','notes','savings_goals',
  'repositories','subscriptions'
];
declare t text;
begin
  foreach t in array tables loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists "own rows on %I" on public.%I;', t, t);
    execute format($p$
      create policy "own rows on %I" on public.%I
      for all
      using (user_id = public.current_user_id())
      with check (user_id = public.current_user_id()) $p$, t, t);
  end loop;
end $$;

-- RLS for rows that only have a parent (no direct user_id): guard through
-- the parent's user_id instead.
alter table public.invoice_payments enable row level security;
drop policy if exists "own invoice payments" on public.invoice_payments;
create policy "own invoice payments" on public.invoice_payments
  for all
  using (
    exists (select 1 from public.invoices i
            where i.id = invoice_payments.invoice_id
              and i.user_id = public.current_user_id())
  )
  with check (
    exists (select 1 from public.invoices i
            where i.id = invoice_payments.invoice_id
              and i.user_id = public.current_user_id())
  );

alter table public.savings_transactions enable row level security;
drop policy if exists "own savings transactions" on public.savings_transactions;
create policy "own savings transactions" on public.savings_transactions
  for all
  using (
    exists (select 1 from public.savings_goals g
            where g.id = savings_transactions.goal_id
              and g.user_id = public.current_user_id())
  )
  with check (
    exists (select 1 from public.savings_goals g
            where g.id = savings_transactions.goal_id
              and g.user_id = public.current_user_id())
  );

alter table public.commits enable row level security;
drop policy if exists "own commits" on public.commits;
create policy "own commits" on public.commits
  for all
  using (
    exists (select 1 from public.repositories r
            where r.id = commits.repository_id
              and r.user_id = public.current_user_id())
  )
  with check (
    exists (select 1 from public.repositories r
            where r.id = commits.repository_id
              and r.user_id = public.current_user_id())
  );

-- Realtime (optional). Enable per-table publication for live updates.
alter publication supabase_realtime add table public.notes;
alter publication supabase_realtime add table public.savings_goals;
alter publication supabase_realtime add table public.savings_transactions;
alter publication supabase_realtime add table public.invoices;